export const mockPendingEntities = [
  {
    id: "pending-1",
    name: "GreenTech Solutions",
    entity_type: "social_enterprise",
    website: "https://example.com/greentech",
    description: "Developing affordable solar solutions for rural communities",
    hq_location: "Sarawak",
    industry_sector: "Clean Energy, Technology",
    submitted_at: "2023-08-01T10:30:00Z",
  },
  {
    id: "pending-2",
    name: "Microfinance Access",
    entity_type: "ecosystem_builder",
    website: "https://example.com/microfinance",
    description: "Supporting financial inclusion through microloans and education",
    hq_location: "Kuala Lumpur",
    industry_sector: "Financial Inclusion",
    submitted_at: "2023-08-02T14:15:00Z",
  },
]

export const mockUpdateLogs = [
  {
    id: "log-1",
    timestamp: "2023-08-01T09:30:00Z",
    action: "update",
    details: "42 rows updated",
    duration: "3 mins",
  },
  {
    id: "log-2",
    timestamp: "2023-08-01T09:25:00Z",
    action: "approve",
    details: "Approved: Sustainable Fisheries",
    duration: "1 sec",
  },
  {
    id: "log-3",
    timestamp: "2023-07-30T14:20:00Z",
    action: "news_refresh",
    details: "35 news items fetched",
    duration: "2 mins",
  },
  {
    id: "log-4",
    timestamp: "2023-07-28T11:15:00Z",
    action: "update",
    details: "56 rows updated",
    duration: "4 mins",
  },
  {
    id: "log-5",
    timestamp: "2023-07-25T16:40:00Z",
    action: "reject",
    details: "Rejected: Invalid entry",
    duration: "1 sec",
  },
]

// Add a default export with mock entities data
export default [
  {
    id: "se-1",
    entity_type: "social_enterprise",
    name: "EcoCycle Berhad",
    slug: "ecocycle-berhad",
    website: "https://example.com/ecocycle",
    description: "EcoCycle is a social enterprise focused on recycling and waste management solutions in urban areas.",
    hq_location: "Kuala Lumpur",
    contact_email: "info@ecocycle.example.com",
    industry_sector: "Waste Management, Environment",
    funding_stage: "Seed",
    last_enriched: "2023-05-15T08:30:00Z",
    news_link_list: ["https://example.com/news/ecocycle-expansion", "https://example.com/news/ecocycle-award"],
    _claim_status: "claimed",
    _approved: true,
  },
  {
    id: "se-2",
    entity_type: "social_enterprise",
    name: "PichaEats",
    slug: "pichaeats",
    website: "https://example.com/pichaeats",
    description: "PichaEats empowers refugee chefs to build livelihoods through a food delivery service.",
    hq_location: "Kuala Lumpur",
    contact_email: "hello@pichaeats.example.com",
    industry_sector: "Food, Social Impact",
    funding_stage: "Growth",
    last_enriched: "2023-06-10T10:15:00Z",
    news_link_list: ["https://example.com/news/pichaeats-expansion", "https://example.com/news/pichaeats-award"],
    _claim_status: "claimed",
    _approved: true,
  },
  {
    id: "inv-1",
    entity_type: "investor",
    name: "Impact Ventures Malaysia",
    slug: "impact-ventures-malaysia",
    website: "https://example.com/impact-ventures",
    description:
      "Impact Ventures Malaysia is an early-stage impact investor focusing on social enterprises in Southeast Asia.",
    hq_location: "Kuala Lumpur",
    contact_email: "invest@impactventures.example.com",
    industry_sector: "Impact Investing, Financial Inclusion",
    cheque_size_range: "USD 50k-500k",
    investment_thesis: "Supporting innovative solutions to social and environmental challenges in Malaysia.",
    last_enriched: "2023-04-20T14:45:00Z",
    news_link_list: [
      "https://example.com/news/impact-ventures-fund",
      "https://example.com/news/impact-ventures-portfolio",
    ],
    _claim_status: "claimed",
    _approved: true,
  },
  {
    id: "eco-1",
    entity_type: "ecosystem_builder",
    name: "Social Innovation Hub",
    slug: "social-innovation-hub",
    website: "https://example.com/sihub",
    description:
      "Social Innovation Hub is an accelerator for social enterprises addressing Malaysia's most pressing challenges.",
    hq_location: "Penang",
    contact_email: "hello@sihub.example.com",
    industry_sector: "Education, Technology",
    program_type: "Accelerator",
    next_intake_date: "2023-09-01",
    last_enriched: "2023-03-05T09:20:00Z",
    news_link_list: ["https://example.com/news/sihub-program", "https://example.com/news/sihub-graduates"],
    _claim_status: "claimed",
    _approved: true,
  },
  {
    id: "se-3",
    entity_type: "social_enterprise",
    name: "Biji-Biji Initiative",
    slug: "biji-biji-initiative",
    website: "https://example.com/biji-biji",
    description:
      "Biji-Biji Initiative is a sustainable design company that upcycles waste materials into furniture and art.",
    hq_location: "Selangor",
    contact_email: "hello@biji-biji.example.com",
    industry_sector: "Sustainable Design, Waste Management",
    funding_stage: "Growth",
    last_enriched: "2023-02-18T11:30:00Z",
    news_link_list: ["https://example.com/news/biji-biji-project", "https://example.com/news/biji-biji-exhibition"],
    _claim_status: "claimed",
    _approved: true,
  },
]
